
project_id = "zjgphamebgrclivvkhmw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

# Only keep essential Edge Functions
[[functions]]
name = "add-trainee"
verify_jwt = true

[[functions]]
name = "update-trainee"
verify_jwt = true

[[functions]]
name = "get-trainees"
verify_jwt = true

[[functions]]
name = "staff-register" 
verify_jwt = false

[[functions]]
name = "trainee-register"
verify_jwt = false

[[functions]]
name = "staff-attendance-view"
verify_jwt = false

[[functions]]
name = "trainee-attendance-view"
verify_jwt = false

[[functions]]
name = "attendance-manage"
verify_jwt = false
