
# Update this file when creating, renaming or removing functions

project_id = "zjgphamebgrclivvkhmw"

[functions.trainee-register]
verify_jwt = true

[functions.trainee-attendance-add]
verify_jwt = true

[functions.trainee-attendance-view]
verify_jwt = true

[functions.staff-attendance-add]
verify_jwt = true

[functions.staff-attendance-view]
verify_jwt = true

[functions.add-trainee]
verify_jwt = true

[functions.update-trainee]
verify_jwt = true

[functions.get-trainees]
verify_jwt = true

[functions.staff-register]
verify_jwt = true

[functions.attendance-service]
verify_jwt = true
