project_id = "jvjvrdarcmdjohdwwfhf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

# Edge Functions
[functions.process-image-upload]
verify_jwt = false

[functions.manage-trainees]
verify_jwt = true

[functions.manage-staff]
verify_jwt = true

[functions.manage-attendance]
verify_jwt = true

[functions.manage-archives]
verify_jwt = true

[functions.register-person]
verify_jwt = false
